{{- $fullName := include "guestbook.fullname" . -}}
{{- $labels := include "guestbook.labels" . | nindent 4}}
{{- $selectorLabels := include "guestbook.selectorLabels" . | nindent 6}}
{{- range $key, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
  {{- $labels }}
    app.service: {{ $key }}
spec:
  replicas: {{ $val.replicaCount }}
  selector:
    matchLabels:
    {{- $selectorLabels }}
      app.service: {{ $key }}
  template:
    metadata:
      labels:
      {{- $labels | indent 4}}
        app.service: {{ $key }}
    spec:
      containers:
      - name: {{ $.Chart.Name }}-{{ $key }}
        image: {{ $val.image.repository }}:{{ $val.image.tag }}
        imagePullPolicy: {{ $val.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ $val.service.port }}
          protocol: TCP
        env:
        - name: PORT
          value: "{{ $val.service.port }}"
        {{- if eq $key "frontend" }}
        - name: GUESTBOOK_API_ADDR
          value: "{{ $fullName }}-backend:{{$.Values.services.backend.service.port}}"
        {{- end }}
        {{- if eq $key  "backend" }}
        - name: GUESTBOOK_DB_ADDR
          value: "{{ $val.dbUrl }}"
        {{- end }}
{{ end }}