{{- $fullName := include "guestbook.fullname" . -}}
{{- $labels := include "guestbook.labels" . | nindent 4}}
{{- $selectorLabels := include "guestbook.selectorLabels" . | nindent 4}}
{{- range $key, $val := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
  {{- $labels }}
    app.service: {{ $key }}
spec:
  type: {{ $val.service.type }}
  ports:
  - port: {{ $val.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
  {{- $selectorLabels }}
    app.service: {{ $key }}
{{ end }}