apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: system
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: ingress-nginx
    version: 3.7.1
  values:
    controller:
      replicaCount: 3
    rbac:
      create: true
