apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets-controller
  createNamespace: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: 1.10.3
  value:
    crd:
      keep: false
