apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: development
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/tag.frontend.services: glob:*
    filter.fluxcd.io/tag.backend.services: glob:*
spec:
  releaseName: guestbook
  chart:
    git: git@github.com:chukaofili/gitops-infra
    path: flux_config/charts/guestbook
    ref: master
  values:
    services:
      frontend:
        image:
          repository: gcr.io/ms-clients-2018/nodejs-guestbook-frontend
          tag: 90b6273
        replicaCount: 1
      backend:
        dbUrl: "mongodb.system:27017"
        image:
          repository: gcr.io/ms-clients-2018/nodejs-guestbook-backend
          tag: 90b6273
        replicaCount: 1