apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: development
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:fluxcd/helm-operator-get-started
    path: flux_config/charts/guestbook
    ref: master
  values:
    frontend:
      image:
        repository: gcr.io/ms-clients-2018/nodejs-guestbook-backend
        tag: 18c4e8f
      replicaCount: 1
    backend:
      dbUrl: "mongodb.system:27017"
      image:
        repository: gcr.io/ms-clients-2018/nodejs-guestbook-backend
        tag: 18c4e8f
      replicaCount: 1